aug_max_zoom: 1.5
aug_max_zoom_rel: 1.015
aug_min_zoom: 0.8
aug_min_zoom_rel: 0.985
aug_rotate: 0.2
aug_trans: 0.2
batch_size: 10
batch_size_val: 10
bilateral_mask: 0
checkpoint: null
checkpoint_exclude_params:
- ''
checkpoint_include_params:
- '*'
checkpoint_mode: null
cuda: true
debug: 0
dropout: 0
evaluation: false
loss_perc: 0
lr_scheduler: MultiStepLR
lr_scheduler_gamma: 0.5
lr_scheduler_last_epoch: -1
lr_scheduler_milestones:
- 54
- 72
- 90
max_save: -1
min_save: -1
model: IRR_PWC_V2
model_div_flow: 0.05
name: run
num_iters: 1
num_workers: 4
optimizer: Adam
optimizer_amsgrad: false
optimizer_betas: !!python/tuple
- 0.9
- 0.999
optimizer_eps: 1.0e-08
optimizer_group: null
optimizer_lr: 0.0001
optimizer_weight_decay: 4.0e-4
random_freeze: 0
save: experiments/chairs
save_conf: true
save_result_bidirection: false
save_result_flo: false
save_result_img: false
save_result_occ: false
save_result_path_name: ''
save_result_png: false
seed: 1
self_attention: 0
seploss: 0
start_epoch: 0
total_epochs: 108
training_augmentation: RandomAffineFlowOcc
training_augmentation_addnoise: true
training_dataset: FlyingChairsOccTrain
training_dataset_photometric_augmentations: true
training_dataset_root: ../data/flying_chairs_occ/FlyingChairsOcc/data
training_key: total_loss
training_loss: MultiScaleEPE_PWC_Bi_Occ_upsample
validation_augmentation: null
validation_dataset: FlyingChairsOccValid
validation_dataset_photometric_augmentations: false
validation_dataset_root: ../data/flying_chairs_occ/FlyingChairsOcc/data
validation_key: epe
validation_key_minimize: true
validation_loss: MultiScaleEPE_PWC_Bi_Occ_upsample
