batch_size: 4
batch_size_val: 1
bilateral_mask: 0
checkpoint: checkpoints/T3/
checkpoint_exclude_params:
- ''
checkpoint_include_params:
- '*'
checkpoint_mode: resume_from_best
crop_min_ratio: 0.95
cuda: true
debug: 0
devices: '0'
dropout: 0
evaluation: false
get_tmp_results: ''
lr_scheduler: MultiStepLR
lr_scheduler_gamma: 0.5
lr_scheduler_last_epoch: -1
lr_scheduler_milestones:
- 616
- 819
- 1022
max_save: -1
min_save: -1
model: IRR_PWC_V2
model_div_flow: 0.05
name: run
num_iters: 1
num_workers: 4
optimizer: Adam
optimizer_amsgrad: false
optimizer_betas: !!python/tuple
- 0.9
- 0.999
optimizer_eps: 1.0e-08
optimizer_group: null
optimizer_lr: 3.0e-05
optimizer_weight_decay: 0
res2net: 0
rewarp: 0
save: experiments/KITTI_comb
save_conf: true
save_result_bidirection: false
save_result_flo: false
save_result_img: false
save_result_occ: false
save_result_path_name: ''
save_result_png: false
seed: 1
self_attention: 0
start_epoch: 160
total_epochs: 710
training_augmentation: RandomAffineFlowOccKITTI
training_augmentation_addnoise: false
training_augmentation_crop: random_v2
training_dataset: KittiCombTrain
training_dataset_photometric_augmentations: true
training_dataset_preprocessing_crop: true
training_dataset_root: ../data/kitticomb/
training_key: total_loss
training_loss: MultiScaleEPE_PWC_Bi_Occ_upsample_KITTI
validation_augmentation: null
validation_dataset: KittiCombVal
validation_dataset_photometric_augmentations: false
validation_dataset_preprocessing_crop: false
validation_dataset_root: ../data/kitticomb/
validation_key: epe
validation_key_minimize: true
validation_loss: MultiScaleEPE_PWC_Bi_Occ_upsample_KITTI
