aug_max_zoom: 1.3
aug_max_zoom_rel: 1.015
aug_min_zoom: 0.8
aug_min_zoom_rel: 0.985
aug_rotate: 0.2
aug_trans: 0.2
bilateral_mask: 0
checkpoint: checkpoints/Sintel_comb_train
checkpoint_exclude_params:
- ''
checkpoint_include_params:
- '*'
checkpoint_mode: resume_from_best
cuda: true
debug: 0
devices: 0,1
dropout: 0
evaluation: 0
loss_perc: 0
lr_scheduler: MultiStepLR
lr_scheduler_gamma: 0.5
lr_scheduler_last_epoch: -1
lr_scheduler_milestones:
- 687
- 720
- 770
model: IRR_PWC_V2
model_div_flow: 0.05
name: run
num_iters: 1
optimizer: Adam
optimizer_amsgrad: false
optimizer_betas: !!python/tuple
- 0.9
- 0.999
optimizer_eps: 1.0e-08
optimizer_group: null
optimizer_lr: 1.0e-05
optimizer_weight_decay: 0
random_freeze: 0
res2net: 0
rewarp: 0
save: experiments/sintel_ft
save_conf: true
save_result_bidirection: false
save_result_flo: false
save_result_img: false
save_result_occ: false
save_result_path_name: ''
save_result_png: false
seed: 1
self_attention: 0
seploss: 0
start_epoch: 450
total_epochs: 790
training_augmentation: RandomAffineFlowOccSintel
training_augmentation_addnoise: false
training_augmentation_crop: random_v2
training_dataset: SintelTrainingFinalTrain
training_dataset_photometric_augmentations: true
training_dataset_root: ../data/sintel/
training_key: total_loss
training_loss: MultiScaleEPE_PWC_Bi_Occ_upsample_Sintel
validation_augmentation: null
validation_dataset: SintelTrainingFinalValid
validation_dataset_photometric_augmentations: false
validation_dataset_root: ../data/sintel/
validation_key: epe
validation_key_minimize: true
validation_loss: MultiScaleEPE_PWC_Bi_Occ_upsample_Sintel
