batch_size: 4
batch_size_val: 4
bilateral_mask: 0
checkpoint: checkpoints/C1
checkpoint_exclude_params:
- ''
checkpoint_include_params:
- '*'
checkpoint_mode: resume_from_best
cuda: true
debug: 0
dropout: 0
evaluation: false
lr_scheduler: MultiStepLR
lr_scheduler_gamma: 0.5
lr_scheduler_last_epoch: -1
lr_scheduler_milestones:
- 128
- 139
- 149
max_save: 0
min_save: 0
model: IRR_PWC_V2
model_div_flow: 0.05
name: run
num_iters: 1
num_workers: 4
optimizer: Adam
optimizer_amsgrad: false
optimizer_betas: !!python/tuple
- 0.9
- 0.999
optimizer_eps: 1.0e-08
optimizer_group: null
optimizer_lr: 1.0e-05
optimizer_weight_decay: 0.0004
rewarp: 0
save: experiments/things
save_conf: true
save_result_bidirection: false
save_result_flo: false
save_result_img: false
save_result_occ: false
save_result_path_name: ''
save_result_png: false
seed: 1
self_attention: 0
seploss: 0
start_epoch: 109
total_epochs: 159
training_augmentation: RandomAffineFlowOcc
training_augmentation_addnoise: true
training_augmentation_crop:
- 540
- 960
training_dataset: FlyingThings3dCleanTrain
training_dataset_photometric_augmentations: true
training_dataset_root: ../data/things/FlyingThings3D_subset/
training_key: total_loss
training_loss: MultiScaleEPE_PWC_Bi_Occ_upsample
validation_augmentation: null
validation_dataset: SintelTrainingCleanFull
validation_dataset_photometric_augmentations: false
validation_dataset_root: ../data/sintel/
validation_key: epe
validation_key_minimize: true
validation_loss: MultiScaleEPE_PWC_Bi_Occ_upsample
